### PR TITLE
Set Tab Toolbar height

### LINKED ISSUE #12: Tab Toolbar size increases with a lot of opened Tabs
I am using your CSS for "Chrome like" theme with Firefox v91 on Debian Linux distribution.

When I open a lot of Tabs (until Tab List button appears), the height for Tab Toolbar is bigger than its original size.
FF-Chrome-2

If I close Tabs (until Tab List button disappears), the height for Tab Toolbar returns to its original size.
FF-Chrome-1

I modified your CSS to fix height of TabsToolbar to 36 pixels => problem fixed when I open a lot of tabs.
`#TabsToolbar { height: 36px !important; }`

I will send you a PR to fix this issue.

### PR DESCRIPTION
**Pull request by lcheylus**
- Closes pratyushtewari/firefox-like-chrome#12

### CODE REVIEW

**Comment by pratyushtewari** [comment]
Thank you for the update and contribution.

**Comment by lcheylus** [comment]
Why did you close this PR without merge ?

**Comment by pratyushtewari** [comment]
Was trying on phone. Not very clear ux. Will try later soon

**Comment by pratyushtewari** [comment]
Hi @lcheylus Sorry for the late merge. I had a baby a few weeks ago and been busy with him lately! Thank you for the PR!

**Pull request merged**
